### PR TITLE
feat: add support for limit/offset

### PR DESCRIPTION
**Pull request by betodealmeida**
# Summary

Closes https://github.com/betodealmeida/shillelagh/issues/223.

# Testing instructions

### CODE REVIEW

File: src/shillelagh/backends/apsw/vt.py [hunk 1]
```diff
@@ -317,8 +352,14 @@ def BestIndex(  # pylint: disable=too-many-locals
                     indexes.append((column_index, sqlite_index_constraint))
                     break
             else:
-                # no indexes supported in this column
-                constraints_used.append(None)
+                if (operator == Operator.LIMIT and self.adapter.supports_limit) or (
+                    operator == Operator.OFFSET and self.adapter.supports_offset
+                ):
+                    constraints_used.append((filter_index, True))
```
Comment (cancan101) [inline src/shillelagh/backends/apsw/vt.py:358]: Does setting this to true / false matter? Are there cases where it should be false? Does it differ for limit vs offset?

File: src/shillelagh/backends/apsw/vt.py [hunk 2]
```diff
@@ -317,8 +352,14 @@ def BestIndex(  # pylint: disable=too-many-locals
                     indexes.append((column_index, sqlite_index_constraint))
                     break
             else:
-                # no indexes supported in this column
-                constraints_used.append(None)
+                if (operator == Operator.LIMIT and self.adapter.supports_limit) or (
```
Comment (cancan101) [inline src/shillelagh/backends/apsw/vt.py:355]: I think you should use `is` here rather than `==`

Comment (betodealmeida) [reply src/shillelagh/backends/apsw/vt.py:355]: Ah, good catch, let me fix it.

File: src/shillelagh/backends/apsw/vt.py (hunk 1 above)
Comment (betodealmeida) [reply src/shillelagh/backends/apsw/vt.py:358]: It matters, but I couldn't find documentation about it. I had to set it to true for it work correctly.

Comment (cancan101) [reply src/shillelagh/backends/apsw/vt.py:358]: I found these docs (at least for offset): https://www.sqlite.org/vtab.html#omit_constraint_checking_in_bytecode

File: src/shillelagh/adapters/base.py [hunk 3]
```diff
@@ -120,6 +125,7 @@ def get_data(
         self,
         bounds: Dict[str, Filter],
         order: List[Tuple[str, RequestedOrder]],
+        **kwargs: Any,
```
Comment (cancan101) [inline src/shillelagh/adapters/base.py:128]: I actually think this was a breaking change for 1.1 release. I am seeing:
```
airtabledb/adapter.py:168: error: Signature of "get_data" incompatible with supertype "Adapter"
airtabledb/adapter.py:16[8](https://github.com/cancan101/airtable-db-api/runs/7884454809?check_suite_focus=true#step:9:9): note:      Superclass:
airtabledb/adapter.py:168: note:          def get_data(self, bounds: Dict[str, Filter], order: List[Tuple[str, Literal[Order.ASCENDING, Order.DESCENDING]]], **kwargs: Any) -> Iterator[Dict[str, Any]]
airtabledb/adapter.py:168: note:      Subclass:
airtabledb/adapter.py:168: note:          def get_data(self, bounds: Dict[str, Filter], order: List[Tuple[str, Literal[Order.ASCENDING, Order.DESCENDING]]]) -> Iterator[Dict[str, Any]]
Found 1 error in 1 file (checked 15 source files)
```

I can fix on my end, but just a heads up.

Comment (betodealmeida) [reply src/shillelagh/adapters/base.py:128]: Oh, thanks for letting me know! But just to confirm, this is a mypy error, right? Adapters written for 1.0.x should still work after upgrading to 1.1.x, so I wouldn't consider this a breaking change, even if this could potentially break CI/CD pipelines.

Comment (cancan101) [reply src/shillelagh/adapters/base.py:128]: Correct, it looks like this will just be a mypy issue (for now). At some point if this code is ever modified to always pass a kwarg, then old adapters will break:
https://github.com/betodealmeida/shillelagh/blob/6cf03406db06a994cefd16bf480935a425045125/src/shillelagh/backends/apsw/vt.py#L488-L492
